# fly.toml app configuration file generated for fareplay-discovery

app = "fareplay-discovery"
primary_region = "sjc"

[build]

[deploy]
  release_command = "npx prisma migrate deploy"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  HOST = "0.0.0.0"
  API_RATE_LIMIT = "100"
  API_RATE_LIMIT_WINDOW = "60000"
  HEARTBEAT_TIMEOUT_MINUTES = "10"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/ready"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

